# Generated by Django 3.1.5 on 2021-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210118_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
    ]
