# Generated by Django 3.1.3 on 2020-12-24 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network',
            field=models.ManyToManyField(null=True, related_name='network', to=settings.AUTH_USER_MODEL),
        ),
    ]
