# Generated by Django 3.1.3 on 2021-01-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonbalance',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonbalance',
            name='owed_user1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonbalance',
            name='owed_user2',
            field=models.BigIntegerField(default=0),
        ),
    ]
