# Generated by Django 3.1.5 on 2021-02-01 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_balance', '0004_auto_20210117_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('inc_debt', models.BigIntegerField(default=0)),
                ('inc_owed', models.BigIntegerField(default=0)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL)),
                ('common_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_account', to='common_balance.commonaccount')),
            ],
        ),
    ]
