# Generated by Django 3.1.5 on 2021-02-01 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_balance', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
